version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 71856
      DB_NAME: postgres
      SECRET_KEY: 123
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      GROQ_API_KEY:
      DB_NAME_TEST: tests
      TESTING: false
    depends_on:
      - db
    volumes:
      - ./backend_data:/app/backend_data

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: 71856
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata: